Fix transition matrix
CardiacModelling/markov-builder pull request #13
Opened 2023-04-28 13:01 UTC by joeyshuttleworth

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically 

## Documentation checklist

- [ ] I have updated all documentation in the code where necessary.
- [ ] I have checked spelling in all (new) comments and documentation.
- [ ] I have added a note to RELEASE.md if relevant (new feature, breaking change, or notable bug fix).

2023-05-03 13:44 UTC, MichaelClerx reviewed
Hi Joey,
Won't have time for an in-depth review (if you want that) till June or after.
Few small comments. And comparison 2 looks plain wrong?
Would plot an error for these 3 cases too (signal1 - signal2)

2023-05-03 13:44 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> -            raise Exception("state_attirbutes_class must be a dataclass")
Uncovered line warning here!

2023-05-03 13:44 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                            row.append(edge["rate"])
Maybe do a find/replace to get all your ' and " use consistent?

2023-05-03 13:44 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                starting_distribution[0] += no_trajectories - starting_distribution.sum()
Should this be indented? What happens if param_dict and starting_distribution are None?

2025-11-20 15:20 UTC, joeyshuttleworth commented
We don't have all 30 yet models yet, but there are some important changes to the transition-rate matrix calculations that it would be good to merge in

2025-11-26 21:08 UTC, MichaelClerx requested changes
Initial review on the start of the main class.
Some patterns are emerging that you can fix elsewhere before I continue

- Try to keep the API minimal, providing access only where needed and using private variables to help the user know what to ignore. The point of a good class is that it hides details from the user
- Don't use logging everywhere in case you want to debug, some day. Avoid the need for debugging by having good tests. Add debug statements only when actually debugging and remove if needed. In Python this code is always run (unlike e.g. C macros), so it will slow things down for no good reason
- Stop calling things x_dict
- Describe all arguments in the class/function docstring.
- If there's any relations between argument (e.g. x is only checked if y has a certain value) then (1) see if you can design it better so that this doesn't occur; (2) if you really can't then check and raise ValueErrors when the user does it wrong; (3) document exactly what the allowable input is

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +        if states:
Since this is typed as a list, with [] as default, it shouldn't be None so you can drop the if and just perform the iteration

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                 = None, auxiliary_params_dict: dict = None):
These should all be explained in the class's docstring. Especially since there seem to be relationships between them (e.g. `shared_variables_dict` is only checked if rates is set

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                 rate_dictionary: dict = None, auxiliary_expression: str =
Names like `rate_dictionary` and `shared_variables_dict` are very annoying. You're not writing `states_list` etc. A dict is one of the fundamental data types. Just call it what it represents, not how it's implemented (not sure if that goes for state_attributes_class cause there's no docstring telling me what that is)

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +            if shared_variables_dict:
I'd write this as
```
for r in rates:
    ...
``` (no if)
and then
if `shared_variables`:
    if rates:
        ...
    else:
      raise ValueError('Shared variables given but no rates supplied.')
```
to tell the user they made an invalid call

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +        if states and open_state and rates and rate_dictionary and auxiliary_expression and\
For readability you might want to combine some of these into a bool that you then check on a new line

W.r.t. rates and states the same logic as above applies (And the way to use these arguments that make requirements on other arguments should all be explained in the docstring)

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                        if isinstance(rate, str):
Why are there different types stored on edges?
Can you e.g. 1) always store whatever the 2nd case is (list? tuple?) or 2) create some datatype that accomodates both but is easier to work with?

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                          else {**self.default_values, **self.shared_variables}[param]
Merging two dicts every iteration feels inefficient

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> -        if states:
Since these graphs don't seem to have any kind of typing, you'll need a big comment above to explain what goes in the graph, what is stored in its nodes, etc.

Also, I'd strongly recommond making as many variables as you can private. It says to the user of this class "You don't need to know how this bit works, leave this to me". If they are public, then define them at class level first and provide a docstring for each

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                 MarkovStateAttributes = None, seed: int = None, name: str =
The docstring is not very clear. How is markov chain also a compartmental model?

The "using networkx" bit is exactly what a good class should hide from the user. If I'm using this class I don't want to know how you implemented it, I just need to know how to use it.

Instead of saying it has various functions and tests, tell me the main ones. Give an example of how I use it

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                 MarkovStateAttributes = None, seed: int = None, name: str =
The () after the classname are unnecessary and best avoided, as it makes it look like a function

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> -        if states:
When deciding what to hide from the user, err on the side of hiding absolute everything. It's easy to provide access later. Initially, only write for the use case you know. If more are found later it's an easy job to provide get/set

2025-11-26 21:08 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
Raise an exception or if you reeeeeeally insist on warning but continuing use warnings.warn()

The `logging` module is for big server applications like apache or a DB or mail server or something.

If you want debug statements just use print and comment them out when not debugging (or simply remove them - again don't program for contingencies and eventualities, deal with them if they happen and add tests for the use cases you expect

2025-11-28 15:13 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                 = None, auxiliary_params_dict: dict = None):
Docstring and __init__ updated

2025-11-28 15:13 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                 rate_dictionary: dict = None, auxiliary_expression: str =
Changed these parameter names

2025-11-28 15:14 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +            if shared_variables_dict:
Simplified the logic here

2025-11-28 15:14 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +        if states and open_state and rates and rate_dictionary and auxiliary_expression and\
Removed this

2025-11-28 15:15 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                        if isinstance(rate, str):
Should always be a string (see add_transition), so removed type checking

2025-11-28 15:16 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                          else {**self.default_values, **self.shared_variables}[param]
Now dicts are merged outside the loop so it's more readable

2025-11-28 15:17 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> -        if states:
Will set things to private in a separate PR.  Want to make a nice version available without breaking anything external too much (my other projects)

2025-11-28 15:22 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                 MarkovStateAttributes = None, seed: int = None, name: str =
First comment is fair, and I've taken it out of the docstring. But I think it might be worth mentioning that this could be used as a way of generating a suitable networkx graph so it can be manipulated / plotted / outputted with other tools. But admittedly, I didn't end up doing any of that.

2025-11-28 15:26 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
I've found logging useful when importing markov builder into other projects. It can be help when debugging code in those projects and I think it can be disabled and the levels can be set externally too. Without this, I might have to have a local version of Markov builder and be editing in print statements. 

Not too bothered, but I think it'd be convenient (for me at least) to keep them in.

2025-12-02 13:19 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +                 MarkovStateAttributes = None, seed: int = None, name: str =
I get that. But it's generally a good guideline to only implement what you need. One good reason (beyond the simplicity and time saving mentioned below) is that it helps you test things: if you add a function you never use, you won't notice if it's broken. Much easier to just add it when you need to

https://dev.to/alisamir/yagni-you-arent-gonna-need-it-a-key-principle-in-software-development-167m

2025-12-02 13:31 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +                 MarkovStateAttributes = None, seed: int = None, name: str =
That's a good point. A lot of things in this package started out as a sort of prototype, so it'd be worth reevaluating what's actually needed

2025-12-02 13:40 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
If you were going very "proper" software dev here, then you'd say you want a "separation of concerns" which says that you would _never_ want to know about markov builder internals from another project, because (1) there shouldn't be any bugs (full unit tests) and (2) the API and documentation should guide your use of the markov builder, not the implementation of that API

For this particular example, I think you want either

1. An exception, because this shouldn't happen so the program should stop, or
2. An exception, which the user code should catch and use to update whatever needs updating (I don't think this is likely here), or
3. A warning (`warnings.warn('This thing happened but code will keep running anyway')`)

A typical use case for a warning would be something like you're reading a file and it's in a newer format than was tested for so you let the user know that it will probably work but is untested. Or you're doing some fancy matrix thing that isn't 100% necessary and it fails so you can continue with an alternative strategy.

In this case I'm pretty sure you want an exception: The user's code is wrong or else this shouldn't happen, so stop

2025-12-02 13:45 UTC, MichaelClerx commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
In particular cause it's a TypeError you're catching here. So its looks like it definitely the user doing it wrong, not markov builder, so you want to say "I can't guarantee the output, because this needs to fixed on your side"?

Worth even testing that they're both set _before_ calling numpy?

2025-12-02 15:23 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
I should have mentioned - this function has been changed now to raise a ValueError in this case.

https://github.com/CardiacModelling/markov-builder/blob/fb544572f8f4131a6455273cc9a79683481a67be/markov_builder/MarkovChain.py#L518

```
    def get_equilibrium_distribution(self, param_dict: dict = {}) -> Tuple[List[str], np.array]:
        """Compute the equilibrium distribution of the CTMC for the specified transition rate values

        :param param_dict: A dictionary specifying the values of each transition rate
        :return: A 2-tuple describing equilibrium distribution and labels defines which entry relates to which state

        :raises ValueError: If not every necessary parameter is defined in param_dict

        """


        A, B = self.eliminate_state_from_transition_matrix(use_parameters=True)
        labels = self.graph.nodes()
        vars_used = [*A.free_symbols, *B.free_symbols]


        for _var in vars_used:
            if str(_var) not in param_dict:
                raise ValueError(f"Error evaluating equilibrium distribution {_var}\n"
                                 f"A={A}\nB={B}\nparams={param_dict}\n")


        ss = -np.array(A.LUsolve(B).evalf(subs=param_dict)).astype(np.float64)
        ss = np.append(ss, 1 - ss.sum())
        return labels, ss
```

I think there was a possibility of a TypeError if you didn't provide a value for some of the parameters. In that case, it tries to evaluate a sympy Symbol as a float.

2025-12-02 15:24 UTC, joeyshuttleworth commented on markov_builder/MarkovChain.py
> +            logging.warning("Error evaluating equilibrium distribution "
But there are still some debug messages elsewhere

2025-12-16 19:06 UTC, joeyshuttleworth commented
All 30 models have been added now. Some fixes have been applied to some of the .mmt files where it looks like there were errors

2025-12-17 08:43 UTC, mirams commented
> All 30 models have been added now. Some fixes have been applied to some of the .mmt files where it looks like there were errors

You'll have to show me those Joey! And do a pull request on the 30 models repo?

2025-12-17 08:45 UTC, mirams commented on tests/models_myokit/model-30.mmt
> +model]]
Typo?

2025-12-17 10:41 UTC, mirams commented on markov_builder/models/thirty_models/model10.py
> +    open_state = 'O'
O * Oh ?

2025-12-17 10:41 UTC, mirams commented on markov_builder/models/thirty_models/model1.py
> +    auxiliary_expression = "g_Kr * state_O * (V - E_Kr)"
Just in terms of how we define the model (this may be a separate issue), it is a bit confusing how some of them have `state_O` in the auxiliary_expression, some have `{}` and then later define `open_state = 'O'` separately. Isn't it easier to write `auxiliary_expression = "g_Kr * O * (V - E_Kr)"` ?

2025-12-17 10:44 UTC, mirams commented on markov_builder/models/thirty_models/model1.py
> +    auxiliary_expression = "g_Kr * state_O * (V - E_Kr)"
If we aren't going to abstract the auxiliary_expression to a higher-level class, than it might as well just be explicit for the particular model?

2025-12-17 11:09 UTC, joeyshuttleworth commented on markov_builder/models/thirty_models/model1.py
> +    auxiliary_expression = "g_Kr * state_O * (V - E_Kr)"
I don't think we should keep the "open_state" variable. Some models have more than one open state, so it's confusing.

You need to write state_O because sympy doesn't like you using the "O" on its own (used for big-O notation).

We can get rid of all the `{}`  and `open_state` stuff

2025-12-17 12:19 UTC, MichaelClerx commented on tests/test_30_models.py
> +    def setUp(self):
Did you mean [setUpClass](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass) here?

The difference is that `setUp` gets called before every `test_x` method in your class, while `setUpClass` is called just once

2025-12-17 12:22 UTC, MichaelClerx commented on tests/test_30_models.py
> +        for i, model in zip(self.model_indices, self.models):
If you wanted, you could get fancy here and use `subTest` https://docs.python.org/3/library/unittest.html#subtests

2025-12-17 12:23 UTC, MichaelClerx commented on tests/test_30_models.py
> +        self.model_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
`list(range(31))`?

2025-12-17 12:25 UTC, MichaelClerx commented on tests/test_30_models.py
> +        self.models = [model_00, model_01, model_02, model_03, model_04,
`[f'model_{i:02}' for i in self.model_indices]` ?

2025-12-17 12:27 UTC, MichaelClerx commented on tests/test_30_models.py
> +        for model in self.models:
Could so something slightly nicer here by using e.g. `for model in self.models if ...`, or using sets e.g. `for model in set(self.models) - set(self.disconnected_models)`
At least, I'd move the if statement to above the logging statement

2025-12-17 12:27 UTC, MichaelClerx commented on tests/test_30_models.py
> +                continue
Confused by this. You'd want the tests to fall over if they weren't configured right

2025-12-17 12:29 UTC, MichaelClerx commented on tests/test_30_models.py
> +        self.model_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
Alternatively, some test that you've (probably) listed the models right.
E.g. self.assertEqual(len(set(model_indices)), 31) and self.assertEqual(len(model_indices), len(models))

2025-12-17 12:31 UTC, MichaelClerx commented on README.md
> -`markov_builder` is a Python package for constructing Markov models of ion-channel kinetics. These models may be thought of as chemical reaction networks where the transition rate matrix depends on t
For diffing, might be good to stick to the gary-latex rule of putting a line break after every full stop

2025-12-17 15:11 UTC, joeyshuttleworth commented on tests/test_30_models.py
> +        for i, model in zip(self.model_indices, self.models):
There's also https://docs.pytest.org/en/stable/how-to/parametrize.html which seems to do exactly what we need here.

I'm not sure which way to go on this, but I'd definitely like to tidy these up so we can see which models are failing if there's a problem

2025-12-17 15:12 UTC, joeyshuttleworth commented on tests/test_30_models.py
> +        self.model_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
I suppose there's no need for the indices list anymore.

Before I had all 30 models (missing 15-29 or something), so I did this manually. 

I think we can drop indices, and do `enumerate` with list(range(31))` as you suggest

2025-12-17 15:34 UTC, MichaelClerx commented on tests/test_30_models.py
> +        for i, model in zip(self.model_indices, self.models):
Sure, but keep in mind `pytest` and `unittest` are two seperate packages

2025-12-17 15:37 UTC, joeyshuttleworth commented on tests/test_30_models.py
> +        for i, model in zip(self.model_indices, self.models):
Yeah. I'm just trying to weigh up if switching to pytest is worth it for this. I think it is, because you can use the `parametrize()` decorator to register each model as a separate test, then do `pytest --lf` to only run those models that failed in the last run. Otherwise, running all the tests can take a few minutes.

2026-07-17 14:03 UTC, joeyshuttleworth commented
I think this is all fine now. I think we should get it merged in soon because I'm using this branch for other projects

2026-07-17 16:38 UTC, mirams commented
`state_O` seems kind of magic to me, like an undefined variable. Do you have to refer to any state like `state_<name>` or is it special because it's 'O'?

If it is something special I would take that out and just rename all the variables, throwing an error if you call one 'O' (or any SymPy keyword or whatever the problem is!)

2026-07-20 12:22 UTC, joeyshuttleworth commented
> `state_O` seems kind of magic to me, like an undefined variable. Do you have to refer to any state like `state_<name>` or is it special because it's 'O'?
> 
> If it is something special I would take that out and just rename all the variables, throwing an error if you call one 'O' (or any SymPy keyword or whatever the problem is!)

It's the same for all of the states - the "_state" prefix is given by the function [get_state_symbol](https://github.com/CardiacModelling/markov-builder/blob/cba5166a73de63016dfa9d250495d2bfa856763b/markov_builder/MarkovChain.py#L880).

We could drop that the prefix, I suppose. But it would be annoying not to use 'O' as a state variable!

2026-07-21 11:44 UTC, MichaelClerx approved these changes

2026-07-21 12:25 UTC, merged